### ISSUE TITLE
Endless scrolling ignores dragging

### ISSUE THREAD

**Issue by lesniakania** [deanmcpherson/react-native-sortable-listview#52] opened 2016-11-23 08:19 UTC
Steps to reproduce:
1. Set a list with elements so that not all of them fits the screen (you have a scroll in the scrollview)
2. Start dragging an item
3. Drag it to the bottom (or top) of the scroll view
4. See that scroll is scrolling endlessly and any movement of the item is ignored.

See gif:

![scrolling-issue](https://cloud.githubusercontent.com/assets/193863/20554684/cf5879a8-b15d-11e6-9843-e9523b4bceb0.gif)

I tried to debug it, but all I noticed is that `onPanResponderMove` is not executed in this case, because component is constantly rerendering (probably because of the `setState` in the `checkTargetElement`) and `scrollAnimation` method is invoking all the time.
`setState -> render -> scrollAnimation -> setState -> render -> scrollAnimation -> ...` and no `onPanResponderMove`

`node: v5.9.0`
`npm: 3.10.8`
`react-native: 0.37` (but previously I had `0.31` and the same issues)

**Comment by milesibastos** [comment] 2017-02-09 12:34
May you provide some code to reproduce this case?

**Comment by lesniakania** [comment] 2017-02-09 17:30
You weren't responding for so long, so I'm no longer using your library actually.
Does it work for you in the minimal setup (having any items, but many enough so they don't fit the screen as I described)?

**Comment by lesniakania** [comment] 2017-02-10 07:07
@milesibastos ok, so I've checked this with the latest version now and the problem is reproducable if you just use your example code but wrap your component with `ScrollView` (even if it has scrolled disabled):

```js
<ScrollView scrollEnabled={false} horizontal={true}>
      <SortableListView ....>
</ScrollView>
```

**Comment by ajostergaard** [comment] 2017-02-11 18:24
@lesniakania Is this a duplicate of #38? By the way, did you find an alternative component that works for your scenario?

**Comment by lesniakania** [comment] 2017-02-12 08:08
Yes, it's a duplicate, sorry. Unfortunately I didn't find any other component, so I implemented my own one...: https://github.com/lesniakania/react-native-draggable-board

**Comment by chetstone** [comment] 2017-07-01 23:42
Closing duplicate #38

**Closed by chetstone** 2017-07-01 23:42 UTC
