### ISSUE TITLE
on longpress the row above immediately falls down behind the pressed one

### ISSUE THREAD

**Issue by ippa** [deanmcpherson/react-native-sortable-listview#48] opened 2016-11-08 21:29 UTC
With just a longpress Without any movement, this happens:
![reorder](https://cloud.githubusercontent.com/assets/13777/20117901/ce55d5d4-a602-11e6-9891-40259e75b233.gif)

**Comment by perqa** [comment] 2016-12-30 08:40
I experience the same problem. As soon as a row becomes active, the row above falls down on top of it, even though the active row hasn't moved at all. Once you start moving around, it works as expected.

I would be grateful for any clues pointing me to a possible solution.

![sortable-listview](https://cloud.githubusercontent.com/assets/960796/21561910/c331239a-ce73-11e6-8596-48afc4f08437.gif)

**Comment by perqa** [comment] 2017-01-04 21:43
Add the line 
``import styles from './Styles/ListviewExampleStyle'``
to the SortableListViewExample file, and things work much better!

**Comment by qcchen** [comment] 2017-01-06 09:08
Hi,
perqa,I meet the same problem as you,but I don't understand how you to solove it.
Add the line import styles from './Styles/ListviewExampleStyle', 
because the 'ListviewExampleStyle' can not find ,
can you tell me how to solve it ,thank you?

**Comment by perqa** [comment] 2017-01-07 13:03
Hi @qcchen! Sorry, I referred to a file outside the current project. I have updated my previous comment to something more useful.

**Comment by qcchen** [comment] 2017-01-09 02:17
Hi,@perqa! thanks,the problem inside the screen is worked well,but Beyond the one screen,the problem is also not Solved.

**Comment by chetstone** [comment] 2017-03-08 19:25
This is mostly fixed by f5c2ae0cc55f3d8c332ee3ba5b8d3eb568520739.
There is still a problem with a long list when it is partially scrolled down and an item close to the top is selected. Closing this, I will file a new issue detailing the problem.

**Closed by chetstone** 2017-03-08 19:25 UTC
