### ISSUE TITLE
Unexpected dragged item position

### ISSUE THREAD

**Issue by AlekseiIvshin** [deanmcpherson/react-native-sortable-listview#101] opened 2017-08-21 12:23 UTC
Hi,
I faced following problem: when I start dragging item, it is presented about 100 px lower (only in my case). 

I found out that problem is in 'layout' param provided by Row component in method 'handleLongPress', precisely speaking field 'pageY'. When I set layout.pageY = frameY, it start working as I expect.

I hope that information will be useful for you.

**Comment by nihgwu** [comment] 2017-08-21 14:07
Can you post a workable demo?

**Comment by eduardojunio** [comment] 2017-08-22 13:26
I'm having the same issue :(

**Comment by cinder92** [comment] 2017-08-30 08:57
same issue here

**Comment by nihgwu** [comment] 2017-08-30 15:42
For those who are facing this issue, can anyone provide a simple demo so I can start to fix it

**Comment by kylanhurt** [comment] 2017-08-31 21:58
@nihgwu How would you like the demo? I've never done a demo for RN before. Do you want a GIF, or expo or react-native-web-player?

I'm having this issue *and* the top of the row being cut off by about 14px or so.

**Comment by kylanhurt** [comment] 2017-08-31 22:38
@nihgwu For me the *offset* issue (topic of this thread / issue) appears to start when upgrading from 0.2.2 to 0.2.3. For reference I am testing on an iPhone 5s (A1533) on iOS v10.3.2, if that helps at all.

**Comment by chetstone** [comment] 2017-08-31 22:51
@kylanhurt By demo I believe he would like an example app. If possible, by modifying the Sortable example app included in this repo to show the problem.

Thanks for the info on your version/platform
Also, a few issues were addressed in 0.2.4, perhaps you could try upgrading to the latest (0.2.5) if you haven't already

**Comment by kylanhurt** [comment] 2017-08-31 23:06
@chetstone Thank you for the quick response. Unfortunately both 0.2.4 and 0.2.5 have both the offset and the cropped top of the row issues, so by using 0.2.2 I reduce the bugs down to only the latter which is hardly noticeable.

I think I am going to try to reproduce the error with your guys' example. I'm not an expert iOS or Android developer but maybe I can still be of some help.

**Comment by kylanhurt** [comment] 2017-08-31 23:54
Literally replaced my entrance point index.js with your example code and there dragged item is offset (south / below of where it should be) by approximately one item's height.

For example, in the photo below my finger is actually pressed down on the 'a' item and had barely moved at all (if at all):
![img_0382](https://user-images.githubusercontent.com/6249205/29949900-e4d89bcc-8e6c-11e7-92f9-88ae856ad90f.png)

On a sidenote by using your example I was able to fix the top / header cropping issue which means that is likely being caused by something in my own code. Hope this helps.

**Comment by kylanhurt** [comment] 2017-09-01 00:35
For the record, if anyone else here was having issues with the top part of the item getting cut off (0.2.2), it appears that having a `justifyContent: 'space-between'` causes the issue (at least in my experience). Sorry if this is off-topic.

**Comment by chetstone** [comment] 2017-09-01 00:53
If I understand correctly, you copied [Sortable/example.js](https://github.com/deanmcpherson/react-native-sortable-listview/blob/5ebc612f235eb78fe7c79ca78bb5cf93792aa025/Sortable/example.js) into your own code (not the older example.js at the top level of this repo). 

Did you try actually building and running the Sortable example app? It's easy to do. I just tried this on my iPhone 6+ (10.3.3) and it works fine. When I press the 'a' item it dims and doesn't move till you drag it at least 1/3 of the way across the item above or below. From your photo it looks like though you're pressing the 'a', the 'is' is being dimmed. That's not right. Somebody's confused about which item is being activated.

**Comment by kylanhurt** [comment] 2017-09-01 01:10
@chetstone Apologies, I definitely did the basic (top-level) example. Not sortable. *If* I get around to testing that out I will let you know but for the time being I have fixed any issues I've been having with 0.2.2 and work demands that I focus on other tasks. Again, thank you for being very responsive.

**Comment by chetstone** [comment] 2017-09-01 02:01
@kylanhurt Thanks for following up
>  I definitely did the basic (top-level) example. Not sortable.

Actually that shouldn't matter -- there is very little difference between them. The point being that there is something in your app that is not there in the simple Sortable example app that is affecting how this works.

**Comment by nihgwu** [comment] 2017-09-01 04:30
I mean providing a minimal demo to reproduce the issue with the latest version(v0.2.5), then I can investigate what's wrong as I don't have this issue in my apps

**Comment by dgurns** [comment] 2017-09-01 14:46
I am also getting the "offset" issue on both iOS and Android.

RN 0.44.2
react-native-sortable-listview 0.2.5

**Comment by computerjazz** [comment] 2017-09-01 17:23
I can also confirm rolling back to 0.2.2 fixed this issue for me.
I do get a warning about `isMounted` being deprecated though.

>Looks like if any non-sortable-listview elements on the screen don't have an explicit height, the sortable-listview has trouble calculating where to measure from.

I'm using a react-navigation stack navigator and tab navigator -- possible the header/tab bar is not an explicit height.

0.2.5
![sortable-broken](https://user-images.githubusercontent.com/6730148/29980459-c7bf78e8-8efe-11e7-8b11-5d112c470597.gif)

0.2.2
![sortable-0 2 2](https://user-images.githubusercontent.com/6730148/29980476-d3b813e4-8efe-11e7-9607-200cfc32cf6f.gif)

**Comment by yudapc** [comment] 2017-09-07 08:21
@computerjazz Yeah, I Agree with you. After downgrade to version 0.2.2 it's works.

**Comment by computerjazz** [comment] 2017-09-07 17:54
@yudapc are you also using react-navigation by any chance? (or do you have any headers/footers that might be causing issues?)

**Comment by dgurns** [comment] 2017-09-07 18:12
I was getting this error and was using react-navigation, yes.

**Comment by eduardojunio** [comment] 2017-09-08 12:55
Confirmed, only happens when using React Navigation headers.

**Comment by nihgwu** [comment] 2017-09-08 14:16
Thanks for reporting, I can confirm this, will figure out how it fix it

**Closed** 2017-09-10 13:26 UTC

**Comment by nihgwu** [comment] 2017-09-13 15:26
@eduardojunio right, I'm a bit busy right now, will fix it by the weekend, stay tuned

**Comment by eduardojunio** [comment] 2017-09-14 00:43
@nihgwu thank you! <3

**Comment by nihgwu** [comment] 2017-09-14 15:07
@eduardojunio @computerjazz I just landed the fix for Android, can you test it, I'd love to hear your feedbacks

**Comment by eduardojunio** [comment] 2017-09-14 15:27
@nihgwu sure! I'll be testing and editing this comment soon.

**Comment by eduardojunio** [comment] 2017-09-14 15:38
@nihgwu now everything is working as expected on both Android and iOS! Thank you very much for such quick solution! <3

**Comment by nihgwu** [comment] 2017-09-14 15:44
@eduardojunio thanks, actually it's me who broke it 😂

**Comment by thangho** [comment] 2018-01-20 04:28
It still error when i move item over screen. Only apear when use with TabNavigator in react-navigation.

I move item 9 to top of screen.

![simulator screen shot - iphone 6s plus - 2018-01-20 at 11 26 32](https://user-images.githubusercontent.com/18325071/35179842-c82c82ae-fdd4-11e7-8c45-528f098e004e.png)
